### PR TITLE
AtomicCell: Use atomic-maybe-uninit

### LINKED ISSUE #315: Soundness of AtomicCell::compare_exchange is dubious
`AtomicCell<T>::compare_exchange` will, if I understand the code correctly, use `AtomucU*::compare_exchange_weak` if `T` has the right size.  But this means that e.g. for `(u8, u16)`, which has size 4, it will transmute these pairs into `u32` and compare them as integers.  However, such pairs contain a padding byte, meaning that the `u32` contains some uninitialized memory.  Having uninitialized memory in a  `u32` is [uncharted territory at best](https://github.com/rust-rfcs/unsafe-code-guidelines/issues/71), but performing actual operations on such a datum (as opposed to just load/store) brings us very close to UB.  I am not sure what the rules are in LLVM for this case, but under the proposed `poison` semantics I think the comparison will return `poison` and hence using it in an `if` is UB.  For Rust, I think the intention is to make any operation on uninitialized data UB (like it is in C), meaning the comparison would already return UB.

Strictly speaking, this affects not just the fast path, but also the arbitrarily-sized case: `bytes_eq` might compare uninitialized bytes.

### LINKED ISSUE #748: `AtomicCell` accessing uninitialized memory
Run the follow code sample with `cargo +nightly miri run`

```rust
use crossbeam_utils::atomic::AtomicCell;

#[allow(dead_code)]
#[repr(align(8))]
#[derive(Copy, Clone, Debug)]
enum Test {
    Field(u32),
    FieldLess,
}

fn main() {
    assert!(AtomicCell::<Test>::is_lock_free());
    let x = AtomicCell::new(Test::FieldLess);
    println!("{:?}", x.load());
}
```

I see the following error from Miri
```
error: Undefined Behavior: type validation failed at .value.<enum-tag>: encountered uninitialized bytes, but expected a valid enum tag
note: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
```

I think the root of this issue is that `AtomicCell` is trying to do a `transmute_copy` on the `None` value, but the upper bits are uninitialized, therefore `AtomicCell` is reading uninitialized data.

crossbeam-utils = "0.8.5"
cargo 1.56.0-nightly (cc17afbb0 2021-08-02)

### PR DESCRIPTION
**Pull request by taiki-e**
This fixes UB when lock-free and the value has uninitialized bytes, by using [atomic-maybe-uninit](https://github.com/taiki-e/atomic-maybe-uninit) crate.
Fixes #315
Fixes #748

Also, this makes 128-bit atomics lock-free on some platforms.
Closes https://github.com/crossbeam-rs/rfcs/issues/13

Currently, this patch always uses fallback (seqlock) on environments that do not support inline assembly, such as Miri.
It is possible to use atomic-maybe-uninit crate to fix UB of concurrent access with volatile read/write in seqlock/deque (#744, #859), but that is not included in this PR and is left to subsequent PRs.

---

cc @RalfJung

### CODE REVIEW

**Comment by taiki-e** [comment]
Currently, it is not possible to use MaybeUninit in the input registers of an inline assembly (i.e., when processing MaybeUninit, values must be [passed through memory](https://github.com/taiki-e/atomic-maybe-uninit/blob/main/src/arch/aarch64.rs#L121-L122)), so this worsens performance.

Before:
```
test concurrent_load_u8     ... bench:     600,658 ns/iter (+/- 11,986)
test concurrent_load_usize  ... bench:     601,385 ns/iter (+/- 11,719)
test concurrent_store_u8     ... bench:   1,358,933 ns/iter (+/- 192,961)
test concurrent_store_usize  ... bench:   1,356,045 ns/iter (+/- 20,230)
```

After (pass by memory):

```
test concurrent_load_u8     ... bench:     868,554 ns/iter (+/- 150,633)
test concurrent_load_usize  ... bench:     851,380 ns/iter (+/- 7,139)
test concurrent_store_u8     ... bench:   2,029,710 ns/iter (+/- 178,712)
test concurrent_store_usize  ... bench:   2,038,341 ns/iter (+/- 196,265)
```

If I change the atomic-maybe-uninit implementation to pass by value using transmute, performance will be equivalent to the current one, but it is UB when the input value contains uninitialized bytes (because it is transmuted to integer).

After (pass by value):

```
test concurrent_load_u8     ... bench:     601,504 ns/iter (+/- 12,824)
test concurrent_load_usize  ... bench:     600,052 ns/iter (+/- 15,885)
test concurrent_store_u8     ... bench:   1,357,697 ns/iter (+/- 211,465)
test concurrent_store_usize  ... bench:   1,357,504 ns/iter (+/- 252,722)
```

It would be nice if the inline assembly could allow MaybeUninit registers as thomcc had [previously proposed](https://rust-lang.zulipchat.com/#narrow/stream/216763-project-inline-asm/topic/MaybeUninit.20in.20asm!).

**Comment by taiki-e** [comment]
Filed https://github.com/rust-lang/rust/pull/114790 to allow MaybeUninit in input and output of inline assembly.

File: crossbeam-utils/src/atomic/atomic_cell.rs [hunk 1]
```diff
@@ -691,124 +928,275 @@ macro_rules! impl_arithmetic {
...
-    }
+atomic_maybe_uninit::cfg_has_atomic_64! {
+    #[cfg(not(crossbeam_no_atomic_64))]
+    impl_arithmetic!(u64, atomic::AtomicU64, "let a = AtomicCell::new(7u64);");
+    #[cfg(not(crossbeam_no_atomic_64))]
+    impl_arithmetic!(i64, atomic::AtomicI64, "let a = AtomicCell::new(7i64);");
+    #[cfg(crossbeam_no_atomic_64)]
+    impl_arithmetic!(u64, fetch_update, "let a = AtomicCell::new(7u64);");
+    #[cfg(crossbeam_no_atomic_64)]
+    impl_arithmetic!(i64, fetch_update, atomic::AtomicI64, "let a = AtomicCell::new(7i64);");
```
Comment (RalfJung) [inline crossbeam-utils/src/atomic/atomic_cell.rs:966]: With `fetch_update` it doesn't take a type, does it?

Also there's a subtle invariant here that `fallback` is only used if regular loads/stores also use the fallback, right? How is that ensured?

**Comment by taiki-e** [comment]
Since this PR was opened we have made many improvements to both atomic-maybe-uninit and the compiler. Resolving performance issue (https://github.com/rust-lang/rust/pull/114790), improving and stabilizing inline assembly support on tier 2 targets (https://github.com/rust-lang/rust/pull/131258, https://github.com/rust-lang/rust/pull/131781, etc.), fixing or avoiding rustc/LLVM bugs, improving code quality (https://github.com/taiki-e/atomic-maybe-uninit/pull/30, etc.), improving platform support (atomic-maybe-uninit currently supports all CPU architectures supported by Rust other than C-SKY), etc.

I think we can now finally merge this.
