### PR TITLE
Fix memory leak in AtomicOption. Closes #142.

### LINKED ISSUE #142: `AtomicOption` should run `Box::drop` on drop.
Right now it's leaking memory and not running destructors. This is necessary:

```rust
impl<T> Drop for AtomicOption<T> {
    fn drop(&mut self) {
        let inner = self.inner.load(Ordering::SeqCst);
        if !inner.is_null() {
            unsafe { Box::from_raw(inner); }
        }
    }
}
```

Playground: https://is.gd/FUK0pr

### PR DESCRIPTION
**Pull request by spacejam**

### CODE REVIEW

File: src/sync/atomic_option.rs [hunk 1]
```diff
@@ -9,6 +9,17 @@ pub struct AtomicOption<T> {
     inner: AtomicPtr<T>,
 }
 
+impl<T> Drop for AtomicOption<T> {
+    fn drop(&mut self) {
+        let inner = self.inner.load(Ordering::Relaxed);
+        if !inner.is_null() {
+            unsafe {
+                Box::from_raw(inner);
```
Comment (jeehoonkang) [inline src/sync/atomic_option.rs]: How about explicitly calling `drop` here?  `drop(Box::from_raw(inner))`
