### PR TITLE
channel: Remove ptr-to-int casts

### LINKED ISSUE #762: channel: stacked borrows violation with -Zmiri-tag-raw-pointers
```sh
MIRIFLAGS="-Zmiri-tag-raw-pointers -Zmiri-disable-isolation -Zmiri-ignore-leaks" \
    cargo miri test -p crossbeam-channel --test mpsc -- select_tests::sync2
```

<details>
<summary> output </summary>

```text
error: Undefined Behavior: trying to reborrow for SharedReadWrite at alloc509444, but parent tag <untagged> does not have an appropriate item in the borrow stack
    --> /Users/taiki/projects/crossbeam/crossbeam-channel/src/flavors/zero.rs:137:22
     |
137  |         let packet = &*(token.zero as *const Packet<T>);
     |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trying to reborrow for SharedReadWrite at alloc509444, but parent tag <untagged> does not have an appropriate item in the borrow stack
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
             
     = note: inside `crossbeam_channel::flavors::zero::Channel::<i32>::write` at /Users/taiki/projects/crossbeam/crossbeam-channel/src/flavors/zero.rs:137:22
     = note: inside `crossbeam_channel::flavors::zero::Channel::<i32>::send` at /Users/taiki/projects/crossbeam/crossbeam-channel/src/flavors/zero.rs:219:17
     = note: inside `crossbeam_channel::Sender::<i32>::send` at /Users/taiki/projects/crossbeam/crossbeam-channel/src/channel.rs:428:41
note: inside `SyncSender::<i32>::send` at crossbeam-channel/tests/mpsc.rs:54:9
    --> crossbeam-channel/tests/mpsc.rs:54:9
     |
54   |         self.inner.send(t).map_err(|cc::SendError(m)| SendError(m))
     |         ^^^^^^^^^^^^^^^^^^
note: inside closure at crossbeam-channel/tests/mpsc.rs:2099:13
    --> crossbeam-channel/tests/mpsc.rs:2099:13
     |
2099 |             tx.send(1).unwrap();
     |             ^^^^^^^^^^
     = note: inside `std::sys_common::backtrace::__rust_begin_short_backtrace::<[closure@crossbeam-channel/tests/mpsc.rs:2095:31: 2100:10], ()>` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:123:18
     = note: inside closure at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:477:17
     = note: inside `<std::panic::AssertUnwindSafe<[closure@std::thread::Builder::spawn_unchecked<[closure@crossbeam-channel/tests/mpsc.rs:2095:31: 2100:10], ()>::{closure#1}::{closure#0}]> as std::ops::FnOnce<()>>::call_once` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9
     = note: inside `std::panicking::r#try::do_call::<std::panic::AssertUnwindSafe<[closure@std::thread::Builder::spawn_unchecked<[closure@crossbeam-channel/tests/mpsc.rs:2095:31: 2100:10], ()>::{closure#1}::{closure#0}]>, ()>` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:406:40
     = note: inside `std::panicking::r#try::<(), std::panic::AssertUnwindSafe<[closure@std::thread::Builder::spawn_unchecked<[closure@crossbeam-channel/tests/mpsc.rs:2095:31: 2100:10], ()>::{closure#1}::{closure#0}]>>` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:370:19
     = note: inside `std::panic::catch_unwind::<std::panic::AssertUnwindSafe<[closure@std::thread::Builder::spawn_unchecked<[closure@crossbeam-channel/tests/mpsc.rs:2095:31: 2100:10], ()>::{closure#1}::{closure#0}]>, ()>` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:133:14
     = note: inside closure at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:476:30
     = note: inside `<[closure@std::thread::Builder::spawn_unchecked<[closure@crossbeam-channel/tests/mpsc.rs:2095:31: 2100:10], ()>::{closure#1}] as std::ops::FnOnce<()>>::call_once - shim(vtable)` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
     = note: inside `<std::boxed::Box<dyn std::ops::FnOnce()> as std::ops::FnOnce<()>>::call_once` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1854:9
     = note: inside `<std::boxed::Box<std::boxed::Box<dyn std::ops::FnOnce()>> as std::ops::FnOnce<()>>::call_once` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1854:9
     = note: inside `std::sys::unix::thread::Thread::new::thread_start` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
```

</details>

If run without `-Zmiri-tag-raw-pointers`, the test succeeds.

cc #578

### PR DESCRIPTION
**Pull request by taiki-e**
This fixes #762 and another stacked borrows violation that seems to have been made detectable by the fix of #762.

### CODE REVIEW

File: crossbeam-channel/src/flavors/zero.rs [hunk 1]
```diff
@@ -177,7 +190,7 @@ impl<T> Channel<T> {
             // heap-allocated packet.
             packet.wait_ready();
             let msg = packet.msg.get().replace(None).unwrap();
-            drop(Box::from_raw(packet as *const Packet<T> as *mut Packet<T>));
+            drop(Box::from_raw(token.zero.0 as *mut Packet<T>));
             Ok(msg)
```
Comment (taiki-e) [inline crossbeam-channel/src/flavors/zero.rs:194]: Another stacked borrows violation that was fixed by this PR is (While `packet` (an immutable reference to heap-allocated Packet) was still valid, Box::from_raw was called)):

```
error: Undefined Behavior: trying to reborrow for Unique at alloc5094412+0x8, but parent tag <14690213> does not have an appropriate item in the borrow stack
    --> /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:977:9
     |
977  |         Box(unsafe { Unique::new_unchecked(raw) }, alloc)
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trying to reborrow for Unique at alloc5094412+0x8, but parent tag <14690213> does not have an appropriate item in the borrow stack
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
             
     = note: inside `std::boxed::Box::<crossbeam_channel::flavors::zero::Packet<i32>>::from_raw_in` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:977:9
     = note: inside `std::boxed::Box::<crossbeam_channel::flavors::zero::Packet<i32>>::from_raw` at /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:921:18
     = note: inside `crossbeam_channel::flavors::zero::Channel::<i32>::read` at /Users/taiki/projects/crossbeam/crossbeam-channel/src/flavors/zero.rs:193:18
     = note: inside `crossbeam_channel::flavors::zero::Channel::<i32>::recv` at /Users/taiki/projects/crossbeam/crossbeam-channel/src/flavors/zero.rs:302:24
     = note: inside `crossbeam_channel::Receiver::<i32>::recv` at /Users/taiki/projects/crossbeam/crossbeam-channel/src/channel.rs:802:43
note: inside `Chan::<i32>::recv` at crossbeam-channel/tests/golang.rs:64:9
    --> crossbeam-channel/tests/golang.rs:64:9
     |
64   |         r.recv().ok()
     |         ^^^^^^^^
note: inside closure at crossbeam-channel/tests/golang.rs:1420:28
    --> crossbeam-channel/tests/golang.rs:1420:28
     |
1420 |                     l[i] = c.recv().unwrap();
     |                            ^
```
