### PR TITLE
Relaxed size constrait of Local (closes #597)

### LINKED ISSUE #597: crossbeam-epoch internal::local_size unit test fails on 32-bit architectures
```
failures:
---- internal::local_size stdout ----
thread 'internal::local_size' panicked at 'assertion failed: `(left == right)`
  left: `2040`,
 right: `1020`', src/internal.rs:379:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    internal::local_size
```

The same error occurs on both i686 and armv7hl, on fedora rawhide, with stable Rust 1.47.0. The test is fine on all 64-bit architectures that are available to me (x86_64, aarch64, ppc64le, and s390x).

Looking at the source code for the failing test
https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-epoch/src/internal.rs#L375

it seems the intent is to check if `Local` is equal or smaller than 2040 bytes (at least that's what the comment says), but the code in the test actually checks for equality: `assert_eq!(2040, core::mem::size_of::<Local>());`, not a "less than or equal" test.

Should this be changed to `assert!(core::mem::size_of::<Local>() <= 2040);` or something like that? I think this value is half the expected value because pointers are half as big on 32-bit architectures ... Or would it make sense to actually compare using a `usize` value (the architecture dependent pointer size)?

PS: Since this looks like an issue in the test and not a code issue, I'll ignore the failure for now, so fixing this is not urgent :)

### PR DESCRIPTION
**Pull request by jeehoonkang**
@decathorpe Thank you for reporting this.  It's also kinda hotfix.  As @taiki-e said, we really need CI for i686 and other 32-bit architectures... (#598).

r? @taiki-e

### CODE REVIEW

File: crossbeam-epoch/src/internal.rs [hunk 1]
```diff
@@ -376,7 +376,7 @@ pub struct Local {
 // https://github.com/crossbeam-rs/crossbeam/issues/551
 #[test]
 fn local_size() {
-    assert_eq!(2040, core::mem::size_of::<Local>());
+    assert!(core::mem::size_of::<Local>() <= 2040, "An allocation of `Local` should be <= 2048 bytes.");
```
Comment (Vtec234) [inline crossbeam-epoch/src/internal.rs:379]: The message disagrees on the size - `2040` or `2048`?

Comment (jeehoonkang) [reply crossbeam-epoch/src/internal.rs:379]: I "guess" the reason is memory allocator would have 8 bytes of overhead.  But it's just a guess, and I'd like to ping @stjepang ...

In any case, I'll improve the assert description.  It's confusing as you said.

Comment (taiki-e) [reply crossbeam-epoch/src/internal.rs:379]: 2040 is the actual size of the current `Local`, so when comparing using `<=`, I think `<= 2048` is fine.

**Comment by decathorpe** [comment]
> @decathorpe Thank you for reporting this. It's also kinda hotfix. As @taiki-e said, we really need CI for i686 and other 32-bit architectures... (#598).

Looks good to me (since this is basically the "fix" I suggested) :) Thanks!

File: crossbeam-epoch/src/internal.rs (hunk 1 above)
Comment (taiki-e) [reply crossbeam-epoch/src/internal.rs:379]: I remembered that it was actually me who added this test (#552). IIRC, I just reduced the number of objects and adjusted it to be less than 2048 bytes, so that 8 bytes has no particular meaning.

Comment (jeehoonkang) [reply crossbeam-epoch/src/internal.rs:379]: It seems it's quite safe to make its size 2048: https://www.facebook.com/notes/facebook-engineering/scalable-memory-allocation-using-jemalloc/480222803919

**Comment by jeehoonkang** [comment]
@taiki-e would you please review again?  I'd like it to be merged before #603

**Review by taiki-e — APPROVED** [review]
bors r+

**Comment by taiki-e** [comment]
bors retry

> warning: spurious network error
